# Generated by Django 3.2.5 on 2021-10-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='profile_pics/img/%y', verbose_name='default.jpg'),
        ),
    ]
